"""Added saved_by

Revision ID: fc9d76f75c69
Revises: 
Create Date: 2020-05-08 11:23:32.790402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9d76f75c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('saved_by', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_results_saved_by_users'), 'results', 'users', ['saved_by'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_results_saved_by_users'), 'results', type_='foreignkey')
    op.drop_column('results', 'saved_by')
    # ### end Alembic commands ###
